### PR TITLE
Combination Lock using Ordered Shots

### PR DESCRIPTION
**Pull request by elementerch**
New level idea with no existing mechanics, also contains the gravity zone level idea from earlier pull request (now closed)

### CODE REVIEW

**Comment by MGPAlpha** [comment]
This looks great, but could you switch the row of doors with the red crate barriers? currently its possible to softlock the level by getting stuck inside the doors, and since i want to integrate the design into a larger level where u carry one crate through several puzzles, so it only really needs to block the crate

**Comment by elementerch** [comment]
Actually I think the earlier issues with some files happened again, I'll try to fix it

**Review by MGPAlpha — CHANGES_REQUESTED** [review]
OrderedShots looks good, although i just realized the other level is in here too. for that one, the end section feels really unclear. The player zone that unlocks the upper door is really unclear, and the way the crate sensor in there is a single-time unlocks runs really counter to what the player has been taught about how they work. Might I suggest instead: a crate sensor is indented into the wall that opens the upper door, and the player has to go in and press a button. then, the player has to get the box back out of the first crate sensor and place it in the second one to open the second exit door.

Also now that i'm thinking about it, i have a couple other issues with that level. First, the first box you encounter doesn't really do anything. You don't have to interact with it at all to solve the puzzle. Second, in this section, 
Screenshot from 2021-10-21 21-39-08
It's possible to softlock the level by sending the box thru the door but not going through with it. Its also possible to go through the door, but not get the box through the door in time, so now you're stuck in the later area without the crate needed to solve it. I'd recommend avoiding any design where you have to bring a crate through the door you use the same crate to open, unless there's a specific other element of the puzzle that prevents softlocking it that way

**Comment by elementerch** [comment]
Can I just remove that level from this pull request and fix it/submit separately?

**Comment by MGPAlpha** [comment]
sure

**Review by MGPAlpha — APPROVED** [review]
looks good

**Pull request merged**
