### PR TITLE
Edge Lighting

### PR DESCRIPTION
**Pull request by alanrtao**
https://user-images.githubusercontent.com/32473511/134118843-043d3e80-4ade-4d8e-b767-1fd068c9f51d.mp4

### CODE REVIEW

**Comment by MGPAlpha** [comment]
Hey, sorry this took me so long to get to. which of the files are responsible for the effect in the video?

**Comment by aelu419** [comment]
@MGPAlpha EdgeManual shader, EdgeManual material, and my scene for demo. To apply, just drag in the EdgeManual material to a sprite renderer and set the parameters (they're in the unit of the original texture's pixel).

**Review by MGPAlpha — CHANGES_REQUESTED** [review]
Ok, this is promising but has some stuff to work out. When I put the shader on the player in a lit level, it ends up turning all white. Basically, it seems like (at the saved material settings) from light intensity .3 to 1 it gets colored from normal sprite color to pure white, while below .3 it just stays at sprite color and never gets darker. By changing the brightness i can make it not go fully white at intensity 1, but it still can never get darker than the base color

Also the .vsconfig is still in the commit

**Comment by aelu419** [comment]
The lighting problem is caused by border width. Changing it back to 1 should do the trick.
image

**Comment by aelu419** [comment]
The preview is in scenes/alan/start_copy, not the old edge shader demo scene.

**Comment by MGPAlpha** [comment]
Ok so a few things here. The edge is a good size now, but the part that isn't on the edge is still totally unaffected by lighting changes. In pitch black it's still visible. Also, some of the files you've changed seem unrelated, and have just changed the line endings. I'm not really sure why those have crlf line endings in the first place, but id like to fix those with a separate pr

**Comment by aelu419** [comment]
The unlit was by design. It's fixed now.

image

**Comment by aelu419** [comment]
@MGPAlpha I went back and started from the main branch of your repo. The LF endings in gitattributes are only applied when I re-add the files to git (remove cached -> add all). At this point I can either

1. PR with CRLF files, but all the changes are relevant
2. PR with LF files, but there's a lot of them
Not sure which one to do.

**Comment by MGPAlpha** [comment]
so the most recent set of changes actually changes several files from LF to CRLF, including about 2/3rds of the scripts folder, and several of the shaders in TextMeshPro. Can you try rebasing from the most recent version of main, and just keeping the changes relevant to the edge lighting?

**Pull request closed without merging**
